"""Serve the pre-built React UI at the application root ``/``.

Static assets are served under ``/static/`` with a 1-hour ``Cache-Control``
header.  ``index.html`` is served with ``no-cache`` and has server
configuration injected as ``window.__SERVER_CONFIG__`` so the React app can
resolve API URLs correctly behind reverse proxies.

PWA files (``sw.js``, ``manifest.webmanifest``, ``workbox-*.js``) are placed
in the build output root by ``vite-plugin-pwa`` and must be served at the
application root path (not under ``/static/``) so the service worker scope
covers the whole app.
"""

from __future__ import annotations

import json
import logging
import mimetypes
import re
from collections.abc import Callable
from pathlib import Path

from fastapi import FastAPI, Request, Response
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles

logger = logging.getLogger(__name__)

_CACHE_MAX_AGE = 3600  # 1 hour


class _CachedStaticFiles(StaticFiles):
    """StaticFiles subclass that adds Cache-Control headers."""

    async def get_response(self, path: str, scope: dict) -> Response:  # type: ignore[override]
        """Return response with cache-control header."""
        response = await super().get_response(path, scope)
        if response.status_code == 200:
            response.headers["Cache-Control"] = f"public, max-age={_CACHE_MAX_AGE}"
        return response


def mount_ui(app: FastAPI, static_dir: Path, prefix: str = "") -> None:
    """Mount the UI at ``{prefix}/`` with static assets under ``{prefix}/static/``.

    Server configuration (``apiBaseUrl``, ``staticUrl``) is injected into
    ``index.html`` as a ``<script>`` tag so the React app can read it from
    ``window.__SERVER_CONFIG__``.  This makes the UI work correctly behind
    reverse proxies and load balancers where the client-facing URL differs
    from the internal server URL.

    The Vite build uses ``base: "./"`` which produces relative ``./js/``,
    ``./css/`` etc. paths in ``index.html``.  These are rewritten to absolute
    ``{prefix}/static/js/``, ``{prefix}/static/css/`` paths at serve time so
    they resolve correctly regardless of the document URL or proxy prefix.

    Args:
        app: The FastAPI application instance.
        static_dir: Path to the directory with built UI files.
        prefix: URL prefix (e.g. ``"/ai/transcribe"``).  Empty string for root.
    """
    _raw_html = (static_dir / "index.html").read_text(encoding="utf-8")
    # Rewrite Vite's relative "./subdir/file" asset paths to absolute
    # "{prefix}/static/subdir/file".  The pattern requires at least one "/"
    # after "./" so root-level files like "./manifest.webmanifest" and
    # "./sw.js" are left untouched — they must be served at {prefix}/filename,
    # not under /static/.
    static_base = f"{prefix}/static"
    index_html = re.sub(
        r'(src|href)="\.\/([^/"]+\/[^"]+)"',
        rf'\1="{static_base}/\2"',
        _raw_html,
    )

    @app.get(f"{prefix}/", response_class=HTMLResponse, include_in_schema=False)
    async def _serve_ui(request: Request) -> HTMLResponse:
        """Serve the SPA index.html with injected server config."""
        # request.base_url already incorporates root_path when uvicorn is started
        # with root_path=prefix, so base correctly reflects the external URL.
        base = str(request.base_url).rstrip("/")
        # ensure_ascii=True escapes all non-ASCII chars; replace </
        # to prevent script injection via closing tags.
        config = json.dumps(
            {"apiBaseUrl": base, "staticUrl": f"{base}/static"},
        ).replace("</", r"<\/")
        config_tag = f"<script>window.__SERVER_CONFIG__={config};</script>"
        html = index_html.replace("</head>", f"{config_tag}</head>", 1)
        return HTMLResponse(
            content=html,
            headers={"Cache-Control": "no-cache"},
        )

    app.mount(
        f"{prefix}/static",
        _CachedStaticFiles(directory=str(static_dir), html=False),
        name="ui-static",
    )

    # --- PWA root-level files ---
    # vite-plugin-pwa places sw.js, manifest.webmanifest, and workbox-*.js in
    # the outDir root.  They must be reachable at {prefix}/filename so the SW
    # scope covers the whole app.  They are NOT under /static/ intentionally.
    _mount_pwa_files(app, static_dir, prefix)

    ui_path = f"{prefix}/" if prefix else "/"
    logger.info(
        "UI mounted at %s (static assets: %sstatic/, root: %s)",
        ui_path,
        ui_path,
        static_dir,
    )


def _mount_pwa_files(app: FastAPI, static_dir: Path, prefix: str) -> None:
    """Register routes for PWA root-level files generated by vite-plugin-pwa.

    ``sw.js`` must be served with a ``Service-Worker-Allowed`` header so the
    SW can control the full ``{prefix}/`` scope.  Workbox runtime chunks are
    served with a long immutable cache since their filenames are content-hashed.

    Args:
        app: The FastAPI application instance.
        static_dir: Path to the directory with built UI files.
        prefix: URL prefix (e.g. ``"/ai/transcribe"``).  Empty string for root.
    """
    sw_scope = f"{prefix}/" if prefix else "/"

    # Known fixed filenames
    _fixed: list[tuple[str, dict[str, str]]] = [
        ("sw.js", {"Cache-Control": "no-cache", "Service-Worker-Allowed": sw_scope}),
        ("manifest.webmanifest", {"Cache-Control": "no-cache"}),
        ("registerSW.js", {"Cache-Control": "no-cache"}),
    ]
    for filename, headers in _fixed:
        fp = static_dir / filename
        if not fp.is_file():
            continue
        mime, _ = mimetypes.guess_type(filename)
        mime = mime or "application/javascript"

        def _make_handler(
            path: Path, media_type: str, hdrs: dict[str, str]
        ) -> Callable:
            async def _handler() -> Response:
                return Response(
                    content=path.read_bytes(), media_type=media_type, headers=hdrs
                )

            _handler.__name__ = f"_serve_{path.stem}"
            return _handler

        app.add_api_route(
            f"{prefix}/{filename}",
            _make_handler(fp, mime, headers),
            include_in_schema=False,
        )
        logger.debug("PWA route registered: %s/%s", prefix, filename)

    # Workbox runtime chunks — content-hashed filenames, long immutable cache
    for fp in static_dir.glob("workbox-*.js"):
        mime, _ = mimetypes.guess_type(fp.name)
        mime = mime or "application/javascript"
        headers = {"Cache-Control": "public, max-age=31536000, immutable"}

        def _make_wb_handler(
            path: Path, media_type: str, hdrs: dict[str, str]
        ) -> Callable:
            async def _handler() -> Response:
                return Response(
                    content=path.read_bytes(), media_type=media_type, headers=hdrs
                )

            _handler.__name__ = f"_serve_{path.stem}"
            return _handler

        app.add_api_route(
            f"{prefix}/{fp.name}",
            _make_wb_handler(fp, mime, headers),
            include_in_schema=False,
        )
        logger.debug("PWA route registered: %s/%s", prefix, fp.name)
